<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domain" nsURI="www.uca.es/modeling/cep/domain" nsPrefix="domain">
  <eClassifiers xsi:type="ecore:EClass" name="CEPDomain">
    <eAnnotations source="gmf.diagram">
      <details key="model.extension" value="domain"/>
      <details key="diagram.extension" value="domain_diagram"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainCreationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="label" value="typeName"/>
      <details key="border.color" value="110,110,110"/>
      <details key="tool.name" value="Event"/>
      <details key="tool.description" value="Add an event"/>
      <details key="resizable" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imagePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventProperties" upperBound="-1"
        eType="#//EventProperty" containment="true" eOpposite="#//EventProperty/referencedEvent">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventProperty">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="label" value="name"/>
      <details key="border.color" value="110,110,110"/>
      <details key="tool.name" value="Event Property"/>
      <details key="tool.description" value="Add an event property"/>
      <details key="resizable" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PropertyTypeValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imagePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedEvent" eType="#//Event"
        eOpposite="#//Event/eventProperties"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventProperties" upperBound="-1"
        eType="#//EventProperty" containment="true" eOpposite="#//EventProperty/referencedEventProperty">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedEventProperty"
        eType="#//EventProperty" eOpposite="#//EventProperty/eventProperties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyTypeValue">
    <eLiterals name="Unknown"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="Integer" value="2"/>
    <eLiterals name="Long" value="3"/>
    <eLiterals name="Double" value="4"/>
    <eLiterals name="Float" value="5"/>
    <eLiterals name="String" value="6"/>
  </eClassifiers>
</ecore:EPackage>
